[package]
name = "flat-engine"
version = "0.0.1"
edition = "2021"


[dependencies]
libc = "0.2.138"

flat-ast = {path = "../flat-ast", version="0.0.1"}
flat-common = {path = "../flat-common", version="0.0.1"}
flat-builtin = {path = "../flat-builtin", version="0.0.1"}